### ISSUE TITLE
question:  setInterval value

### ISSUE THREAD

**Issue by ddikodroid** [gchumillas/clockodoro#4]
first, thank you for making this app open-sourced. 

i'm curious why the interval is 333 instead of 1000? could you explain to me. 

```
  React.useEffect(() => {
    const updateTime = () => setTime(dayjs())
    const i = setInterval(() => updateTime(), 333)
    updateTime()
    return () => clearInterval(i)
  }, [])
```

**Comment by gchumillas** [comment]
I found that setInterval is not precise enough and was constantly skipping seconds. For example:

```
1--2--3--4--5--6-- // this is the real time
1----2----4----5--- // this is the setInterval
```

So I decided to use 1/3 seconds (approx. 333 milliseconds), as it is not an expensive operation. It would probably work with other values lower than 1000.

**Comment by ddikodroid** [comment]
> I found that setInterval is not precise enough and it was constantly skipping seconds. For example, in this scenario the app jumps from 3 to 5:
> 
> ```
> 1--2--3--4--5--6-- // this is the real time
> 1---2---3---5---6- // this is the setInterval function
> ```
> 
> So I decided to use 1/3 seconds (approx. 333 milliseconds), as it is not an expensive operation. It would probably work with other values lower than 1000.

i just know this. thank you for the explanation.
